### ISSUE TITLE
Баг с отменой карты

### ISSUE THREAD

**Issue by lxngren** [es3n1n/durak-bot#2]
После того, как человек отменяет карту, вылетает такая ошибка:

2024-10-26 15:15:17.527 | WARNING  | durak_bot.durak.handlers.mode:add_cards:37 - No cards to add, pressing done
Exception in thread Thread-3 (receive_messages):
Traceback (most recent call last):
  File "C:\Users\metxcash\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\metxcash\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\metxcash\Downloads\durak-bot-master\durakonline\socket_listener.py", line 145, in receive_messages
    handler(message)
  File "C:\Users\metxcash\Downloads\durak-bot-master\durak_bot\durak\handlers\rejects.py", line 13, in on_rt_event
    if data['e'] == 1:
       ~~~~^^^^^
KeyError: 'e'

**Comment by es3n1n** [comment]
elaborate please

**Comment by lxngren** [comment]
От лица игрока: https://imgur.com/a/5qRwPj6
Что при этом делает бот (по логам):
![{FE3AB780-8324-4F5E-9089-0C0F861EF8C5}](https://github.com/user-attachments/assets/a8c5e076-5909-4c7a-9e9e-1715c180e58b)

**Comment by Kastet2123** [comment]
@es3n1ncan you help me install the bot?

**Comment by Kastet2123** [comment]
@lxngren можешь тг свое дать ?
